# Zotero for references


## Introduction to projecticum

One of the topics Nutricia Research is interested in tackling is sarcopenia. Sarcopenia is the progressive loss of muscle mass, and is often witnessed in older individuals This poses a problem, because there is a significant correlation between the loss of muscle mass and negative outcomes like prolonged hospital stays, increased risk of infections and noninfectious complications, and higher overall mortality rates. [@boirieFastDigestiveProteins2018]

Sarcopenia has multiple contributing factors. Some of these factors include reduced physical activity, heightened oxidative stress, an inflammatory state, changes in hormonal levels, resistance to muscle-building processes, and inadequate nutrition. [@vandijkImprovedMuscleFunction2016]        

Older adults require a higher amount of protein in their diet compared to younger ones. This is important for their overall health, aid in recovery from illness, and maintain their physical abilities. As people age, their bodies undergo changes in protein metabolism. To help these older individuals (those that are older than 65 years) maintain body mass and function, it is recommended that their average daily protein per kilogram of body weight per day ranges between 1.0 to 1.2. It is also recommended that older individuals undergo both endurance- and resistance-type exercises at levels that are safe and tolerated. And the one's that are exercising at a more frequent level should have a protein intake of around 1.2 grams per kilogram body weight per day. [@bauerEvidenceBasedRecommendationsOptimal2013]

Leucine is one of the most important amino acid for protein synthesis. It is a nutritionally essential branched-chain amino acid (BCAA). Leucine is one of the most abundant amine acids in high quality protein foods. By activating the mammalian target of rapamycin (mTOR) signaling in skeletal muscle, adipose tissue and placental cells, leucine increases protein synthesis. Leucine also promotes metabolism of energy (by uptake of glucose, mitochondrial biogenesis and fatty acid oxidation) in order to fulfill the energy needs that are needed for protein synthesis. Furthermore, leucine plays a part in inhibiting protein degradation. Approximately 20% of Leucine is converted to alfa-ketoisocaproate (alfa-KIC) and beta-hydroxy-beta-methylbutyrate (HMB) in skeletal muscle. It has been hypothesized that the functions of these metabolites are responsible for the effects of Leucine on the muscles. That is why these metabolites have also received considerable attention as nutritional supplements. [@duanRoleLeucineIts2016]

Nutricia Research is aware of the effects that Leucine provides in regards to protein synthesis and the inhibition of protein degradation. This is why Nutricia Research is experimenting with adding Leucine to plant based diets to make these diets more viable for protein synthesis.

For the projecticum, me and 2 classmates are going to be visualising a complex dataset of amino acid concentrations in mice (plasma) put on different diets. The difficulty of this project stems from the fact that for every experimental group (5 groups) there are multiple mice, where each mice have 21 concentrations of amino acids in plasma. 

The negative control in this experiment is the group fasted (F) where the mice fasted and amino acids concentrations were measured. The positive control for this experiment is whey (W). These groups are shown in this paper [@dijkDifferentialEffectsLeucine2018]


## References


